environment:
  nodejs_version: "22" # самая последняя стабильная версия

branches: # какие ветки отслеживаются
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование, чтобы node_modules работал быстрее

install:
  - echo "Starting npm install..." # логи
  - npm install # команда установки зависимостей
  - echo "npm install finished" # логи

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run test  # скрипт тестирования