environment:
  nodejs_version: "22" # самая последняя стабильная версия

branches: # какие ветки отслеживаются
  only:
    - master  # ветка git
    - main

# cache: node_modules  # кеширование, чтобы node_modules работал быстрее

install:
  - npm install  # команда установки зависимостей

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования
